apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: payment
spec:
  template:
    metadata:
      name: payment-v1
      annotations:
    spec:
      containers:
        # Replace Project name userXX-cloudnativeapps with project in which payment is deployed
      - image: image-registry.openshift-image-registry.svc:5000/userXX-cloudnativeapps/payment:latest
