apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: auth-policy
  namespace: user3-catalog
spec:
  targets:
  - name: catalog-springboot
  origins:
  - jwt:
      issuer: http://sso-user3-rhsso.apps.cluster-boston-a877.boston-a877.open.redhat.com/auth/realms/istio
      jwks_uri: http://sso-user3-rhsso.apps.cluster-boston-a877.boston-a877.open.redhat.com/auth/realms/istio/protocol/openid-connect/certs
  principalBinding: USE_ORIGIN